using MotoLube.Domain.Entities;
using System.Linq.Expressions;

namespace MotoLube.Domain.Repositories;

/// <summary>
/// Defines a generic contract for a repository that provides asynchronous and synchronous operations for managing
/// entities by their identifiers.
/// </summary>
/// <remarks>This interface abstracts common data access operations such as insertion, retrieval, update, and
/// existence checks for entities. It is intended to be implemented by classes that interact with a data store,
/// providing a consistent API for working with entities regardless of the underlying storage mechanism. Implementations
/// are expected to handle thread safety and data consistency according to their specific requirements.</remarks>
/// <typeparam name="TId">The type of the unique identifier for entities managed by the repository. Must be non-null and support equality
/// comparison.</typeparam>
/// <typeparam name="TEntity">The type of the entity managed by the repository. Must be a reference type.</typeparam>
public interface IRepository<TEntity, in TId> 
    where TEntity : BaseEntity<TId>
    where TId : IEquatable<TId>
{
    /// <summary>
    /// Asynchronously inserts a new entity into the data store.
    /// </summary>
    /// <param name="entity">The entity to insert. Cannot be null.</param>
    /// <returns>A task that represents the asynchronous insert operation. The task result contains the inserted entity,
    /// including any updated values generated by the data store.</returns>
    Task<TEntity> InsertAsync(TEntity entity);

    /// <summary>
    /// Asynchronously retrieves an entity by its unique identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the entity to find.</param>
    /// <returns>A value task representing the asynchronous operation. The result contains the entity if found; otherwise, <see
    /// langword="null"/>.</returns>
    ValueTask<TEntity?> FindByIdAsync(TId id);

    /// <summary>
    /// Retrieves a read-only collection containing a single page of results, projected to the specified result type.
    /// </summary>
    /// <remarks>Throws an exception if the page index is negative or if the page size is less than one. The
    /// total number of available pages is not returned by this method.</remarks>
    /// <typeparam name="TResult">The type to which each entity is projected in the result collection.</typeparam>
    /// <param name="page">The zero-based index of the page to retrieve. Must be greater than or equal to 0.</param>
    /// <param name="size">The number of items to include in each page. Must be greater than 0.</param>
    /// <param name="selector">An expression that defines how to project each entity to the result type.</param>
    /// <param name="cancellationToken">A cancellation token that can be used to cancel the asynchronous operation.</param>
    /// <returns>A read-only collection of results of type TResult for the specified page.</returns>
    Task<IReadOnlyCollection<TResult>> GetPagedListAsync<TResult>(
        int page,
        int size,
        Expression<Func<TEntity, TResult>> selector,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves a read-only collection containing a page of entities from the data source asynchronously.
    /// </summary>
    /// <remarks>Use this method to retrieve entities in a paginated manner, which is useful for large data
    /// sets. The method can be canceled by providing a cancellation token. Ensure that the page and size parameters are
    /// within valid ranges to avoid unexpected results.</remarks>
    /// <param name="page">The zero-based index of the page to retrieve. Must be greater than or equal to 0.</param>
    /// <param name="size">The number of entities to include in the page. Must be greater than 0.</param>
    /// <param name="cancellationToken">A cancellation token that can be used to cancel the asynchronous operation.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains a read-only collection of entities
    /// for the specified page. The collection is empty if no entities are found for the given page.</returns>
    Task<IReadOnlyCollection<TEntity>> GetPagedListAsync(
        int page, 
        int size, 
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Asynchronously returns the total number of items in the collection.
    /// </summary>
    /// <returns>A task that represents the asynchronous operation. The task result contains the total number of items in the
    /// collection.</returns>
    Task<int> CountAsync();
    
    /// <summary>
    /// Deletes the specified entity from the data store.
    /// </summary>
    /// <param name="entity">The entity to delete. Cannot be null.</param>
    void Delete(TEntity entity);
}